name: Update Poultry and Red Meat data

on:
#   schedule:
#     - cron: '0 0 3 * *'
  push:
    branches:
      - 1-fix-chromedriver-pipeline-error

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Run docker job
        run: |
            docker build -t csvscraper .
            ### Running the container
            docker run -v ./data:/usr/src/app/data -p 8081:8081 -e MASTERLIST_URL='https://raw.githubusercontent.com/ai-cfia/PoultryRedMeatCond/1-fix-chromedriver-pipeline-error/data/ADH-717%20-%20Poultry%20and%20Red%20Meat%20data.csv' -e NEW_REPORT_URL='https://aimis-simia.agr.gc.ca/rp/index-eng.cfm?action=pR&pdctc=&r=278' csvscraper

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: 'Update Poultry and Red Meat data'
          add: 'data'
          new_branch: 'testing'